-- MySQL Script generated by MySQL Workbench
-- Thu Jul 22 14:49:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema p7_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema p7_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `p7_test` DEFAULT CHARACTER SET utf8 ;
USE `p7_test` ;

-- -----------------------------------------------------
-- Table `p7_test`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p7_test`.`users` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(50) NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `password` CHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p7_test`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p7_test`.`posts` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `date_issue` DATETIME NOT NULL,
  `body` TEXT NULL,
  `users_id` MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `p7_test`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
